[package]
name = "DeepSeekTUI"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.13.3", features = ["json", "rustls"] }
serde_json = "1.0.148"
dotenvy = "0.15"
anyhow = "1.0.102"
serde = { version = "1.0.228", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }
ratatui = "0.30"
ratatui-textarea = "0.8"
crossterm = "0.29"
tracing = "0.1"
tracing-subscriber = "0.3"
